/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PageContent = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'footer' : IDL.Text,
  'header' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, PageContent))],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHomePage' : IDL.Func([], [PageContent], ['query']),
  'getPage' : IDL.Func([IDL.Text], [IDL.Opt(PageContent)], ['query']),
  'getPages' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Tuple(IDL.Text, PageContent))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removePage' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updatePage' : IDL.Func([IDL.Text, PageContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PageContent = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'footer' : IDL.Text,
    'header' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, PageContent))],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHomePage' : IDL.Func([], [PageContent], ['query']),
    'getPage' : IDL.Func([IDL.Text], [IDL.Opt(PageContent)], ['query']),
    'getPages' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Tuple(IDL.Text, PageContent))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removePage' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updatePage' : IDL.Func([IDL.Text, PageContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };